name = "glevatar"
version = "0.1.2"
description = "Easily create Gravatar URLs in Gleam"
gleam = ">= 1.0.0"

licences = ["MIT"]
repository = { type = "github", user = "bunopnu", repo = "glevatar" }

[dependencies]
gleam_stdlib = "~> 0.36"
glesha = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 1.1"

[javascript.deno]
allow_read = ["./"]
