name = "glevatar"
version = "0.1.0"
description = "Easily create Gravatar URLs in Gleam"

licences = ["MIT"]
repository = { type = "github", user = "bunopnu", repo = "glevatar" }

[dependencies]
gleam_stdlib = "~> 0.31"
glesha = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 0.11"

[javascript.deno]
allow_read = ["./"]
